---
name: based-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: akmods
    install:
    - v4l2loopback
    nvidia-driver: nvidia-open
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
    install:
      packages:
        - brightnessctl
        - fish
        - git-credential-libsecret
        - kdeconnectd
        - kitty
        - libva-nvidia-driver
        - mangowm
        - niri
        - nix
        - noctalia-shell
        - nvidia-container-toolkit
        - nvidia-vaapi-driver
        - playerctl
        - tailscale
        - xorg-x11-drv-nvidia-cuda
      exclude:
        - alacritty
        - waybar
        - swaylock
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '24h'
  - type: signing
