---
name: based-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
    install:
      packages:
        - brightnessctl
        - fish
        - kdeconnectd
        - kitty
        - mangowm
        - nix
        - niri
        - noctalia-shell
        - playerctl
        - tailscale
      exclude:
        - alacritty
        - waybar
        - swaylock
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '24h'
  - type: signing
