---
name: based-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    #repos:
      #nonfree: negativo17
      #copr:
      #  - chronos/apx
    install:
      packages:
       # - apx
        - DankMaterialShell
        - fish
        - nix
        - niri
        - wezterm
      exclude:
        - alacritty
        - waybar
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '24h'
  - type: signing
